# Generated by Django 6.0.5 on 2026-08-22 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier business name', max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medicine commercial name', max_length=150)),
                ('generic_name', models.CharField(blank=True, help_text='Generic formula/active ingredient', max_length=150, null=True)),
                ('batch_number', models.CharField(help_text='Manufacturer batch number', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current available stock quantity')),
                ('minimum_stock', models.PositiveIntegerField(default=10, help_text='Stock alert threshold')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('storage_location', models.CharField(blank=True, help_text='Shelf/Rack location', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Unit selling price', max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions (+), negative for sales/reductions (-)')),
                ('reference_id', models.CharField(blank=True, help_text='Related Purchase/Sale ID', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity purchased')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Unit purchase price', max_digits=10)),
                ('batch_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.medicine')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
